# Software (Package) Implementation and Testing {#sec-software}

```{r}
#| label: setup
#| include: false

# Load packages
library(tidyverse)
library(gt)

# Set default ggplot theme for document
theme_set(theme_classic())
# If using kableExtra tables, print blank cells instead of `NA`
options(knitr.kable.NA = "")

# Load data
load("data/temp_wnba.RData")
```

Motivation + mention how we address the gap in presence of scalable well-tested tool

## Set-up and Example Data

Multi-dimensional contingency table with an ordinal response variable and a set of categorical (nominal/ordinal) explanatory variables/predictors

## Types of Input Data Supported

XXX

dat, txt, csv - for cases form

np.arry directly with adjacent dicts - for contingency table

## Checkerboard copula score (especially an ordinal response variable)

XXX

## Checkerboard copula Regression (CCR)

XXX

## CCR Prediction and Visualization 

-  Point Prediction of the category of the ordinal dependent variable 

- Uncertainty Evaluation of the CCR prediction using nonparametric bootstrap 


## (Scaled) Checkerboard copula Regression Association Measure

- (S)CCRAM : quantify the regression association identified by Checkerboard Copula Regression and its prediction.

- Uncertainty Evaluation of the estimated (S)CCRAMs using nonparametric bootstrap distribution and its confidence interval

- Statistical significance of the estimated (S)CCRAMs using Permutation distribution and its hypothesis testing

## Visualization of Dependence Structures

XXX

## Software Architecture and Design Principles

XXX

## Testing, Validation, and Performance Evaluation

XXX

## User Documentation and Example Workflows

XXX
